UNC-Libraries/chompb

src/main/java/edu/unc/lib/boxc/migration/cdm/CLIMain.java, src/main/java/edu/unc/lib/boxc/migration/cdm/CdmExportCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/InitializeProjectCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/model/MigrationProject.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/CdmExportService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/AbstractCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/CdmExportCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/CdmExportServiceTest.java
https://jira.lib.unc.edu/browse/BXC-3171
* Adds command and service for exporting CDM records as XML based on field config for small collections that don't requiring exporting in pages
=> BXC-3171 - Unpaged record exports

pom.xml, src/main/java/edu/unc/lib/boxc/migration/cdm/CLIMain.java, src/main/java/edu/unc/lib/boxc/migration/cdm/CdmExportCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/CdmIndexCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/exceptions/StateAlreadyExistsException.java, src/main/java/edu/unc/lib/boxc/migration/cdm/model/CdmFieldInfo.java, src/main/java/edu/unc/lib/boxc/migration/cdm/model/MigrationProject.java, src/main/java/edu/unc/lib/boxc/migration/cdm/model/MigrationProjectProperties.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/CdmExportService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/CdmIndexService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/util/ProjectPropertiesSerialization.java, src/test/java/edu/unc/lib/boxc/migration/cdm/CdmIndexCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/CdmIndexServiceTest.java, src/test/resources/gilmer_fields.csv, src/test/resources/sample_exports/export_1.xml, src/test/resources/sample_exports/export_2.xml
https://jira.lib.unc.edu/browse/BXC-3173
* Adds a command and services to produce a sqlite database containing exported records from CDM, using the retrieved field information to produce the schema
* Adds properties to keep track of export and indexing state.
=> BXC-3173 - Index of flat collections

pom.xml, src/main/java/edu/unc/lib/boxc/migration/cdm/AccessFilesCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/CLIMain.java, src/main/java/edu/unc/lib/boxc/migration/cdm/SourceFilesCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/model/MigrationProject.java, src/main/java/edu/unc/lib/boxc/migration/cdm/model/MigrationProjectProperties.java, src/main/java/edu/unc/lib/boxc/migration/cdm/model/SourceFilesInfo.java, src/main/java/edu/unc/lib/boxc/migration/cdm/options/SourceFileMappingOptions.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/AccessFileService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/DestinationsService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/SourceFileService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/AccessFilesCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/SourceFilesCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/CdmIndexServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/SourceFileServiceTest.java, src/test/resources/sample_exports/export_1.xml
https://jira.lib.unc.edu/browse/BXC-3175
* Add command for generating source file mappings
* supports matching files from a base directory against a field from the CDM export, using regular expressions to transform the value of the field to match the expected filename
* Produces a CSV document with the mappings
* Allows for the CSV document to be update based on the result of subsequent generation commands
* Add command for generating access file mappings, which works the same as source file mappings
=> BXC-3175 - Generate source and access file mappings

src/test/java/edu/unc/lib/boxc/migration/cdm/services/GroupMappingServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/SourceFileServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/test/OutputHelper.java
Add helper for consuming output from tests, use it for some of the dry run tests since otherwise intellij can't run them
=> Catch output to prevent intellij test failures

src/main/java/edu/unc/lib/boxc/migration/cdm/model/MigrationProject.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/RedirectMappingService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/SipService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/SipServiceTest.java
This PR adds a redirect mapping service that generates a CSV with the following pieces of information in each row:
- CDM collection ID
- CDM object ID
- Box-c work ID
- Box-c file ID
The RedirectMappingService gets initialized (CSV is opened) at the beginning of the `generateSips` method and closed in its `finally` block. Every time a fileObject is generated, a row gets added to the CSV.
Lastly, there are four new SipsService tests for the new service.
https://jira.lib.unc.edu/browse/BXC-3177
=> Bxc 3177 mapping csvs

src/main/java/edu/unc/lib/boxc/migration/cdm/model/CdmFieldInfo.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/CdmIndexService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/DescriptionsService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/GroupMappingService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/SipService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/SourceFileService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/status/ProjectStatusService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/status/StatusQueryService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/StatusCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/CdmIndexServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/SipServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/SourceFileServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/test/SipServiceHelper.java, src/test/resources/keepsakes_fields.csv, src/test/resources/sample_exports/export_compounds.xml
https://jira.lib.unc.edu/browse/BXC-3228
* Adds support for migration of compound objects, which are predefined multi-file works in CDM
* Supports migration of compound object children
* Compound children don't have the reserved CDM fields that their parent objects do (like cdmid, last modified, etc), so some refactoring of how lists of fields are calculated to account for this. Made some related variables into instance variables instead of method params to cut down on redundancy
* Exclude grouped works from description generation command, since they cannot have descriptions associated with them and cause errors when generating SIPs
* Test helper updates to support testing with other example collections
=> BXC-3228 - Compound object support

src/main/java/edu/unc/lib/boxc/migration/cdm/CdmExportCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/options/CdmExportOptions.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/CdmExportService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/CdmListIdService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/export/ExportState.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/export/ExportStateService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/CdmExportCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/CdmExportServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/CdmListIdServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/export/ExportStateServiceTest.java
https://jira.lib.unc.edu/browse/BXC-3335
* Export operations will attempt to pick up after the last page listed or exported in order to support export of large collections in the case the process is interrupted
* In order to totally restart an export, the `-f` flag will need to be provided if an export was previously started or completed.
* The user will be alerted if an export is resuming, or if they are being prevented from starting a new one.
* Since there are a few major stages to the export process (counting objects, listing ids, exporting metadata), implementation is a simple state machine, with state persisted to a json file, plus a flat text file for recording object ids.
* Updates to related services to bring them more in line with services developer later, and because the list …
=> BXC-3335 - Support resumption of export operations

pom.xml, src/main/java/edu/unc/lib/boxc/migration/cdm/CdmExportCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/export/ExportProgressService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/export/ExportState.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/export/ExportStateService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/util/DisplayProgressUtil.java, src/test/java/edu/unc/lib/boxc/migration/cdm/AbstractOutputTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/export/ExportProgressServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/export/ExportStateServiceTest.java
https://jira.lib.unc.edu/browse/BXC-3336
* Adds service which displays progress of export operations
* Runs in its own thread on a timer, based on monitoring the current export state
* ExportState records the number of objects listed so far
* Pulled in utility for rendering progress bars from bxc3 migration util
* Test method for asynchronous output testing added to help with monitor progress display
* Excluding slf4j-simple dependency which was causing some confusion when debugging a test
=> BXC-3335 - Display export progress

src/test/java/edu/unc/lib/boxc/migration/cdm/test/RedirectMappingHelper.java
We need to allow nulls in the cdm_object_id field in the redirect_mappings table. The tables on the server are created by hand, but this change allows the test suite to have the same specifications.
=> BXC-3422 allowing cdm_object_id to be null

pom.xml
https://jira.lib.unc.edu/browse/BXC-3428
* Add dependency to redirect log4j to slf4j, to resolve a missing log4j implementation warning from poi
=> BXC-3428 - Fix Log4j warning message

src/main/java/edu/unc/lib/boxc/migration/cdm/options/CdmExportOptions.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/CdmExportService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/CdmIndexService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/CdmExportCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/CompleteMigrationIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/CdmExportServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/CdmIndexServiceTest.java, src/test/resources/sample_pages/gilmer_3_page_all.json
https://jira.lib.unc.edu/browse/BXC-3490
* If a configured field is no present for a record or a compound child, then store an empty string for that field. This is to account for some admin fields in cdm not being returned in exports, particularly for compound children
* Change default page size for exports, since CDM is losing ids when exporting 1000 at a time for some collections
* Add verification step to ensure that no ids are missing from an export before declaring export a success.
=> BXC-3490 - Skip missing fields, catch missing records

src/main/java/edu/unc/lib/boxc/migration/cdm/CdmExportCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/CdmFieldsCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/DescriptionsCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/InitializeProjectCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/ProjectPropertiesCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/StatusCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/CdmFieldService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/CdmIndexService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/CdmListIdService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/status/AbstractStatusService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/status/DescriptionsStatusService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/status/DestinationsStatusService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/status/GroupMappingStatusService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/status/SourceFilesStatusService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/CdmFieldServiceTest.java
[https://jira.lib.unc.edu/browse/BXC-3498](https://jira.lib.unc.edu/browse/BXC-3498)
This PR includes improvements to error reporting when chompb operations fail. Small changes were made to services and commands.
- Services: change how errors are thrown
- Commands: add stacktrace to migration.log
=> Bxc 3498 improve error handling

src/main/java/edu/unc/lib/boxc/migration/cdm/GroupMappingCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/GroupMappingService.java
Bug fix to support https://jira.lib.unc.edu/browse/BXC-3288 but does not complete it
=> BXC-3288 - Escape field names during grouping sync

src/main/java/edu/unc/lib/boxc/migration/cdm/model/GroupMappingInfo.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/DescriptionsService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/GroupMappingService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/SipService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/status/GroupMappingStatusService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/GroupMappingCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/GroupMappingServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/SipServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/test/SipServiceHelper.java, src/test/resources/mods_collections/grouped_mods.xml
https://jira.lib.unc.edu/browse/BXC-3679
https://jira.lib.unc.edu/browse/BXC-3680
* Single member groups will not be added to the group mapping file (they were already being excluded when syncing mappings back to the database)
* Group key is now the matched value with a prefix, and the matched value field has been removed from the CSV
* Matching between MODS files and group generated works is now based on the group key
* Removed assignment of primary objects from works (for multifile works, such as groups, it was assigning every file as a primary object, and we don't need primary objects in the migration)
=> BXC-3679/3680 - Group mapping ids

src/main/java/edu/unc/lib/boxc/migration/cdm/SourceFilesCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/options/SourceFileMappingOptions.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/SourceFileService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/SourceFilesCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/SourceFileServiceTest.java
https://jira.lib.unc.edu/browse/BXC-3838
Add flag to allow for generation of source file mappings without doing any actual mapping
=> BXC-3838 - Enable generation of empty source_files.csv mapping file

src/main/java/edu/unc/lib/boxc/migration/cdm/DestinationsCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/options/DestinationMappingOptions.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/DestinationsService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/DestinationsCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/test/SipServiceHelper.java
This PR adds the ability to add a custom destination mapping by specifying a CDM ID (or comma-delimited list of IDs). It will add a new row to the destination mappings file specifying the CDM ID, the destination mapping and collection (if included).
https://jira.lib.unc.edu/browse/BXC-3835
=> Bxc 3835 new destination mapping command

src/main/java/edu/unc/lib/boxc/migration/cdm/CLIMain.java, src/main/java/edu/unc/lib/boxc/migration/cdm/MigrationTypeReportCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/MigrationTypeReportService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/MigrationTypeReportCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/MigrationTypeReportServiceTest.java, src/test/resources/post_migration_report.csv
[https://jira.lib.unc.edu/browse/BXC-3881](https://jira.lib.unc.edu/browse/BXC-3881)
- add new `report_migration_types` command to output the counts of new migrated works and files, will only run after post_migration_report.csv is generated
=> Bxc 3881 postmigration object type report

src/main/java/edu/unc/lib/boxc/migration/cdm/services/SourceFileService.java
This bugfix makes it so the generateMappings code doesn't need the export Filename if the Blank option is chosen:
https://jira.lib.unc.edu/browse/BXC-3926
=> BXC-3926 adjust query and loop to not depend on file name

src/main/java/edu/unc/lib/boxc/migration/cdm/CdmIndexCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/CdmIndexService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/CdmIndexCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/CdmIndexServiceTest.java
https://jira.lib.unc.edu/browse/BXC-3943
* Since CDM doesn't escape reserved XML characters, added a preprocessing step that identifies tags versus contents, then reconstructs the document using JDOM's API so that the content gets XML escaped.
* (sorry for the 2008 looking state machine, I tried using a regex but it threw StackOverflowErrors for long fields)
* Some collections reference CPD files that don't exist, so rather than failing the whole thing, it skips the special CPD processing for affected records and logs a warning
* Removes unwanted control characters which cause XML parsing to fail
=> BXC-3943 - Indexing failures

src/main/java/edu/unc/lib/boxc/migration/cdm/services/CdmIndexService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/CdmExportCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/CdmIndexServiceTest.java, src/test/resources/descriptions/monograph/image/196.cpd, src/test/resources/descriptions/monograph/index/description/desc.all, src/test/resources/monograph_fields.csv
https://jira.lib.unc.edu/browse/BXC-3959
- adjusts for monograph cpd structure differences in assigning children compound objects
- adds tests for exporting and indexing
- adds cpd and desc.all files for test monograph object
=> Bxc 3959 monograph support

src/main/java/edu/unc/lib/boxc/migration/cdm/GroupMappingCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/model/MigrationProjectProperties.java, src/main/java/edu/unc/lib/boxc/migration/cdm/options/GroupMappingSyncOptions.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/CdmFieldService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/GroupMappingService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/sips/WorkGeneratorFactory.java, src/main/java/edu/unc/lib/boxc/migration/cdm/status/GroupMappingStatusService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/status/ProjectStatusService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/GroupMappingCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/SourceFilesCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/CdmFieldServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/GroupMappingServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/SipServiceTest.java, src/test/resources/descriptions/grouped_gilmer/index/description/desc.all, src/test/resources/mods_collections/grouped_mods.xml
https://jira.lib.unc.edu/browse/BXC-4128
* When syncing group works back into the database, chompb will capture order of files within works, where the children are ordered by a user specified CDM field (defaults to "file")
* Some refactoring to break up large method
* Update grouped work sip generation test to use a more appropriate dataset, update some related test resources to work better with sip generation.
=> BXC-4128 - Grouped work ordering

src/test/java/edu/unc/lib/boxc/migration/cdm/services/CdmExportServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/CdmFieldServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/PostMigrationReportServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/PostMigrationReportVerifierTest.java
[https://unclibrary.atlassian.net/browse/BXC-4299](https://unclibrary.atlassian.net/browse/BXC-4299)
- replace initMocks() with openMocks()
- add AutoCloseable instance variable and close the mocks
=> BXC-4299 replace deprecated MockitoAnnotations.initMocks

src/main/java/edu/unc/lib/boxc/migration/cdm/FilterIndexCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/options/IndexFilteringOptions.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/IndexFilteringService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/FilterIndexCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/IndexFilteringServiceTest.java
[https://unclibrary.atlassian.net/browse/BXC-4286](https://unclibrary.atlassian.net/browse/BXC-4286)
- add `--include-range-start`, `--include-range-end`, `--exclude-range-start`, `--exclude-range-end` options
- `IndexFilteringService`: modify `buildQueryFilters` to allow include/exclude range
- `FilterIndexCommand`: add exceptions to `ValidateOptions`
- add tests, remove unused imports
=> Bxc 4286 extend filter index

src/main/java/edu/unc/lib/boxc/migration/cdm/options/DestinationMappingOptions.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/ArchivalDestinationsService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/ArchivalDestinationsServiceTest.java
[https://unclibrary.atlassian.net/browse/BXC-4303](https://unclibrary.atlassian.net/browse/BXC-4303)
- create `ArchivalDestinationsService`
- add `generateCollectionNumbersList` method: generate unique list of values for provided field name
- add fieldName option to `DestinationMappingOptions`
=> BXC-4303 Generate list of collection numbers

pom.xml, src/main/java/edu/unc/lib/boxc/migration/cdm/model/BxcEnvironment.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/ArchivalDestinationsService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/IndexFilteringService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/ArchivalDestinationsServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/test/BxcEnvironmentHelper.java
[https://unclibrary.atlassian.net/browse/BXC-4304](https://unclibrary.atlassian.net/browse/BXC-4304)
- add SolrJ to `pom.xml`
- add `SolrServerUrl` property to `BxcEnvironment`
- `ArchivalDestinationsService`: add `generateCollectionNumbersToPidMapping` method, initialize, solr setters, tests
- fix import in `IndexFilteringService` (tests wouldn't run without doing this)
=> BXC-4304 map coll nums to pids

src/main/java/edu/unc/lib/boxc/migration/cdm/services/ArchivalDestinationsService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/ArchivalDestinationsServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/status/DestinationsStatusServiceTest.java
[https://unclibrary.atlassian.net/browse/BXC-4305](https://unclibrary.atlassian.net/browse/BXC-4305)
- `addArchivalCollectionMappings`: method to add archival collection mappings to destination.csv
=> BXC-4305 update destinations.csv with archival coll mappings

src/main/java/edu/unc/lib/boxc/migration/cdm/services/CdmIndexService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/CdmIndexServiceTest.java, src/test/resources/descriptions/plantations/cdm_fields.csv, src/test/resources/descriptions/plantations/index/description/desc.all
https://unclibrary.atlassian.net/browse/BXC-4336
* Retain newlines in the middle of fields value, so that we can keep line breaks in transcript/full text fields. Whitespace/newlines at the beginning and end of a fields value will still be trimmed off.
=> BXC-4336 - Retain newlines in multiline fields

src/main/java/edu/unc/lib/boxc/migration/cdm/services/ArchivalDestinationsService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/SipService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/sips/CdmToDestMapper.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/ArchivalDestinationsServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/SipServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/test/SipServiceHelper.java
[https://unclibrary.atlassian.net/browse/BXC-4306](https://unclibrary.atlassian.net/browse/BXC-4306)
- `SipService`: move `initializeDestinations` to end of `initDependencies`, add mapping by archival collection number, add `listCdmIdsByArchivalCollectionId` method, add test
- `ArchivalDestinationsService`: write csv file, add default destination and test
- `CdmToDestMapper`: switch mapping id from DestinationMapping to String
- `SipServiceHelper`: add `generateArchivalDestinationMapping`
=> BXC-4306 Map SIPs to destinations by archival coll num

src/main/java/edu/unc/lib/boxc/migration/cdm/model/MigrationProject.java, src/main/java/edu/unc/lib/boxc/migration/cdm/model/PermissionsInfo.java, src/main/java/edu/unc/lib/boxc/migration/cdm/options/PermissionMappingOptions.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/PermissionsService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/PermissionsServiceTest.java
[https://unclibrary.atlassian.net/browse/BXC-4377](https://unclibrary.atlassian.net/browse/BXC-4377)
- `MigrationProject`: add `PERMISSIONS_FILENAME` constant and `getPermissionsPath`
- `PermissionsInfo`: permission mapping info for a project
- `PermissionMappingOptions`: current options include `--cdm-id`, `--everyone`, -`-authenticated`,  and `--force` and `--staff-only` flags
- `PermissionsService`: add methods `generateDefaultPermissions` and `loadMappings`; helper methods `removeMappings`, `ensureMappingState`, `getPatronRoles`; and tests
=> BXC-4377 default work permissions

src/main/java/edu/unc/lib/boxc/migration/cdm/model/PermissionsInfo.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/SipService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/sips/WorkGenerator.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/sips/WorkGeneratorFactory.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/PermissionsServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/SipServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/test/SipServiceHelper.java
[https://unclibrary.atlassian.net/browse/BXC-4379](https://unclibrary.atlassian.net/browse/BXC-4379)
- `PermissionsInfo`: add `getDefaultMapping` and `getMappingByCdmId` methods
- `PermissionsServiceTest`: add test for `getDefaultMapping` and `getMappingByCdmId`
- `SipService`: add `PermissionsInfo` to `initDependencies`
- `SipServiceTest`: add test for generating sips with permissions
- `WorkGenerator`: `addPermission` helper method which takes a CDM ID and a Resource and adds the appropriate literal properties
=> BXC-4379 apply patron permissions in sips

src/main/java/edu/unc/lib/boxc/migration/cdm/PermissionsCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/validators/PermissionsValidator.java, src/test/java/edu/unc/lib/boxc/migration/cdm/PermissionsCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/PermissionsServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/validators/PermissionsValidatorTest.java
[https://unclibrary.atlassian.net/browse/BXC-4380](https://unclibrary.atlassian.net/browse/BXC-4380)
- `PermissionsCommand`: add `validate` subcommand and tests
- `PermissionsValidator`: add `validateMappings` method, `getPatronRoles` helper method, and tests
=> BXC-4380 validate permissions

src/main/java/edu/unc/lib/boxc/migration/cdm/options/PermissionMappingOptions.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/PermissionsService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/PermissionsCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/PermissionsServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/SipServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/test/SipServiceHelper.java
[https://unclibrary.atlassian.net/browse/BXC-4410](https://unclibrary.atlassian.net/browse/BXC-4410)
- `PermissionMappingOptions`: remove `--id` option, add `--with-default` flag
- `PermissionsService`: use `--with-default` flag
- add/modify tests
=> BXC-4410 adjust permissions cmd for default

src/main/java/edu/unc/lib/boxc/migration/cdm/PermissionsCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/options/PermissionMappingOptions.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/PermissionsService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/PermissionsCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/PermissionsServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/test/SipServiceHelper.java
[https://unclibrary.atlassian.net/browse/BXC-4411](https://unclibrary.atlassian.net/browse/BXC-4411)
- `PermissionMappingOptions`: add `--with-works` and `--with-files` flags
- `PermissionsService`: rename `generateDefaultPermissions` method to `generatePermissions`, modify `generatePermissions` to add works/files to csv, add `getIds` helper method
- add tests
=> BXC-4411 add work and file entries to permissions cmd

src/main/java/edu/unc/lib/boxc/migration/cdm/PermissionsCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/options/PermissionMappingOptions.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/PermissionsService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/DestinationsCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/FilterIndexCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/PermissionsCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/ArchivalDestinationsServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/IndexFilteringServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/PermissionsServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/SipServiceTest.java, src/test/resources/descriptions/grouped_gilmer/index/description/desc.all
[https://unclibrary.atlassian.net/browse/BXC-4412](https://unclibrary.atlassian.net/browse/BXC-4412)
- `PermissionsCommand`: add `set` command
- `PermissionMappingOption`: add `--cdm-id` option
- `PermissionsService`: add `setPermissions` method, `updateCsvRecords` helper method, `previousStatePermissions` instance variable
- add tests
=> BXC-4412 basic set command

src/main/java/edu/unc/lib/boxc/migration/cdm/services/sips/WorkGenerator.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/SipServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/test/SipServiceHelper.java
[https://unclibrary.atlassian.net/browse/BXC-4413](https://unclibrary.atlassian.net/browse/BXC-4413)
- `WorkGenerator`: add file permissions to source files
- add tests for compound objects and grouped works with all permissions, only work permissions, and only file permissions
=> BXC-4413 sip generation for file permissions

src/main/java/edu/unc/lib/boxc/migration/cdm/model/PermissionsInfo.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/PermissionsService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/validators/PermissionsValidator.java, src/test/java/edu/unc/lib/boxc/migration/cdm/PermissionsCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/PermissionsServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/validators/PermissionsValidatorTest.java
[https://unclibrary.atlassian.net/browse/BXC-4415](https://unclibrary.atlassian.net/browse/BXC-4415)
- `PermissionsInfo`: add object_type column to csv headers
- `PermissionsService`: add object_type column to permissions csv, modify `queryForMappedIds` to return a map of mapped ids and object types, add `isWork` helper method
- `PermissionsValidator`: change csvRecord size from 3 to 4
- update tests
=> BXC-4415 add object_type column to permissions csv

src/main/java/edu/unc/lib/boxc/migration/cdm/services/PermissionsService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/PermissionsCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/PermissionsServiceTest.java
[https://unclibrary.atlassian.net/browse/BXC-4486](https://unclibrary.atlassian.net/browse/BXC-4486)
- `PermissionsService`: modify `updateCsvRecords` to accept `--with-works` and `--with-files` options
- add and modify tests
=> BXC-4486 add with-works and with-files to perms set cmd

src/main/java/edu/unc/lib/boxc/migration/cdm/services/StreamingMetadataService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/StatusCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/CdmFieldServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/FieldAssessmentTemplateServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/StreamingMetadataServiceTest.java, src/test/resources/descriptions/mini_gilmer/index/description/desc.all, src/test/resources/gilmer_fields.csv
[https://unclibrary.atlassian.net/browse/BXC-4510](https://unclibrary.atlassian.net/browse/BXC-4510)
- `StreamingMetadataService`: service to get streaming AV metadata, add methods `verifyRecordHasStreamingMetadata` and `getStreamingMetadata`
- add streaming metadata to `mini_gilmer`
=> BXC-4510 add StreamingMetadataService

src/main/java/edu/unc/lib/boxc/migration/cdm/SipsCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/SipService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/sips/WorkGenerator.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/sips/WorkGeneratorFactory.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/SipServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/test/SipServiceHelper.java
[https://unclibrary.atlassian.net/browse/BXC-4511](https://unclibrary.atlassian.net/browse/BXC-4511)
- `WorkGenerator`: `addStreamingMetadata` method to add `streamingUrl` property to file objects
- add test
=> BXC-4511 add streaming metadata to SIPS

src/main/java/edu/unc/lib/boxc/migration/cdm/AggregateFilesCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/SourceFilesCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/StatusCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/SipService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/StreamingMetadataService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/status/ProjectStatusService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/status/SourceFilesStatusService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/validators/SourceFilesValidator.java, src/test/java/edu/unc/lib/boxc/migration/cdm/AggregateFilesCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/SourceFilesCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/SipServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/status/SourceFilesStatusServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/test/SipServiceHelper.java, src/test/java/edu/unc/lib/boxc/migration/cdm/validators/SourceFilesValidatorTest.java
[https://unclibrary.atlassian.net/browse/BXC-4512](https://unclibrary.atlassian.net/browse/BXC-4512)
- `SipService` and `SourceFilesValidator`; update validation process in sip generation to consider a file to have a source file mapped to it if streaming metadata fields are present
- `StreamingMetadataService`: switch private method `hasProjectStreamingMetadataField` to public
- add setters/initialize `StreamingMetadataService` in `AggregateFilesCommand`, `SourceFilesCommand`, `StatusCommand`, `ProjectStatusService`, `SourceFilesStatusService`
- fix tests
=> BXC-4512 permit streaming metadata for source file validation

src/main/java/edu/unc/lib/boxc/migration/cdm/GroupMappingCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/model/GroupMappingInfo.java, src/main/java/edu/unc/lib/boxc/migration/cdm/options/GroupMappingOptions.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/GroupMappingService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/sips/WorkGenerator.java, src/test/java/edu/unc/lib/boxc/migration/cdm/GroupMappingCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/PermissionsCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/AggregateFileMappingServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/GroupMappingServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/PermissionsServiceTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/SipServiceTest.java
[https://unclibrary.atlassian.net/browse/BXC-4603](https://unclibrary.atlassian.net/browse/BXC-4603)
- `GroupMappingOptions`: modify`groupField` option to accept a list
- `GroupMappingService`: update `generateMapping` method to use helper methods `generateOneGroupMapping` or `generateMultipleGroupMappings` depending on number of group fields
- add/fix tests
=> BXC-4603 group by multiple fields

src/main/java/edu/unc/lib/boxc/migration/cdm/status/SourceFilesSummaryService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/status/SourceFilesSummaryServiceTest.java
The issue was that when the number of newly mapped files was less than the sample_size, we would end up with an interval of 0, which produced a divide by zero when selecting every Nth result to display. 
For example, if there was one new file mapped, and the sample size was 20, then we would calculate the interval of results to display by doing 1/20, which comes out to 0 since the values are integers.
https://unclibrary.atlassian.net/browse/BXC-4621
* Add test to replicate divide by zero during reporting error, and set minimum interval to 1
=> BXC-4621 - Divide by zero in source_file generate status

src/main/java/edu/unc/lib/boxc/migration/cdm/CLIMain.java, src/main/java/edu/unc/lib/boxc/migration/cdm/ExportObjectsCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/model/ExportObjectsInfo.java, src/main/java/edu/unc/lib/boxc/migration/cdm/model/MigrationProject.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/ExportObjectsService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/ExportObjectsCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/ExportObjectsServiceTest.java
[https://unclibrary.atlassian.net/browse/BXC-4651](https://unclibrary.atlassian.net/browse/BXC-4651)
- add `ExportObjectsService`, `ExportObjectsCommand`, `ExportObjectsInfo`, and tests
- `CLIMain`: add `ExportObjectsCommand` to list of subcommands
- `MigrationProject`: add `getExportObjectsPath`
=> BXC-4651 export_objects command

src/main/java/edu/unc/lib/boxc/migration/cdm/status/ProjectStatusService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/StatusCommandIT.java
[https://unclibrary.atlassian.net/browse/BXC-4728](https://unclibrary.atlassian.net/browse/BXC-4728)
- exclude group/compound objects from `totalObjects` in `chompb status` source files reporting
=> BXC-4728 update source files reporting

src/main/java/edu/unc/lib/boxc/migration/cdm/PermissionsCommand.java
[https://unclibrary.atlassian.net/browse/BXC-4733](https://unclibrary.atlassian.net/browse/BXC-4733)
add acceptable values for patron roles to `permissions generate` help text
=> BXC-4733 update permissions generate help text

src/main/java/edu/unc/lib/boxc/migration/cdm/CLIMain.java, src/main/java/edu/unc/lib/boxc/migration/cdm/ProcessSourceFilesCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/jobs/VelocicroptorRemoteJob.java, src/main/java/edu/unc/lib/boxc/migration/cdm/model/BxcEnvironment.java, src/main/java/edu/unc/lib/boxc/migration/cdm/options/ProcessSourceFilesOptions.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/SourceFilesToRemoteService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/util/SshClientService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/AbstractOutputTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/ProcessSourceFilesCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/jobs/VelocicroptorRemoteJobTest.java, src/test/java/edu/unc/lib/boxc/migration/cdm/test/TestSshServer.java
https://unclibrary.atlassian.net/browse/BXC-4689
* Adds command for starting velocicroptor job and transferring files
* Adds config for boxctron interactions
* Adjustments to job so that it can specify different hosts for transferring versus executing scripts
* Improve response handling
=> BXC-4689 - Source File Processing Command

src/main/java/edu/unc/lib/boxc/migration/cdm/ProcessSourceFilesCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/jobs/VelocicroptorRemoteJob.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/ListProjectsService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/ListProjectsCommandIT.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/ListProjectsServiceTest.java
[https://unclibrary.atlassian.net/browse/BXC-4688](https://unclibrary.atlassian.net/browse/BXC-4688)
Add `processingJobs` field to `list_projects` command. Each job will have a `pending` or `completed` status. Currently, the only job is velocicropter.
=> BXC-4688 add processingJobs field to list projects cmd

src/main/java/edu/unc/lib/boxc/migration/cdm/services/CdmIndexService.java, src/test/java/edu/unc/lib/boxc/migration/cdm/services/CdmIndexServiceTest.java, src/test/resources/descriptions/pdf/image/17941.cpd, src/test/resources/descriptions/pdf/index/description/desc.all, src/test/resources/pdf_fields.csv
[https://unclibrary.atlassian.net/browse/BXC-4768](https://unclibrary.atlassian.net/browse/BXC-4768)
- detect when object is `Document-PDF` and skip over its children
- set `ENTRY_TYPE_FIELD` / `cdm2bxc_entry_type` to `doc-pdf`
=> BXC-4768 ignore pdf children

src/main/java/edu/unc/lib/boxc/migration/cdm/ProcessSourceFilesCommand.java, src/main/java/edu/unc/lib/boxc/migration/cdm/services/SourceFilesToRemoteService.java, src/main/java/edu/unc/lib/boxc/migration/cdm/util/SshClientService.java
https://unclibrary.atlassian.net/browse/BXC-4808
* Allow a much longer time for ssh timeouts, but keep timeout the same for auth
* Keep sessions alive for duration of thread, rather than a new one for every transfer. 
* Create all of the parent directories up front, rather than scattered throughout file transfers, and avoid extra calls. 
* Use futures so that we can get the error back from transfers and have the job fail rather than progress is a file doesn't transfer
=> BXC-4808: Improve transfer reliaability
