UNC-Libraries/chompb

src/main/java/edu/unc/lib/boxc/migration/cdm/CLIMain.java
src/main/java/edu/unc/lib/boxc/migration/cdm/DestinationsCommand.java
src/main/java/edu/unc/lib/boxc/migration/cdm/model/DestinationsInfo.java
src/main/java/edu/unc/lib/boxc/migration/cdm/model/MigrationProject.java
src/main/java/edu/unc/lib/boxc/migration/cdm/model/MigrationProjectProperties.java
src/main/java/edu/unc/lib/boxc/migration/cdm/options/GenerateDestinationMappingOptions.java
src/main/java/edu/unc/lib/boxc/migration/cdm/services/DestinationsService.java
src/test/java/edu/unc/lib/boxc/migration/cdm/AbstractCommandIT.java
src/test/java/edu/unc/lib/boxc/migration/cdm/CdmExportCommandIT.java
src/test/java/edu/unc/lib/boxc/migration/cdm/CdmFieldsCommandIT.java
src/test/java/edu/unc/lib/boxc/migration/cdm/CdmIndexCommandIT.java
src/test/java/edu/unc/lib/boxc/migration/cdm/DestinationMappingCommandIT.java
src/test/java/edu/unc/lib/boxc/migration/cdm/InitializeProjectCommandIT.java

https://jira.lib.unc.edu/browse/BXC-3208
* Adds command for generating basic one destination mapping files, and some infrastructure for later more complicated cases

BXC-3208 - Basic destination mapping

---

README.md

https://jira.lib.unc.edu/browse/BXC-3236
View updated readme here:
https://github.com/UNC-Libraries/cdm-to-boxc-migration-util/blob/bxc-3236-readme/README.md

BXC-3236 - Expand readme with usage and installation instructions

---

src/main/java/edu/unc/lib/boxc/migration/cdm/model/DestinationSipEntry.java
src/test/java/edu/unc/lib/boxc/migration/cdm/services/SipServiceTest.java

https://jira.lib.unc.edu/browse/BXC-3260

BXC-3260 - New collections will be created with public access settings

---

src/main/java/edu/unc/lib/boxc/migration/cdm/CLIMain.java
src/main/java/edu/unc/lib/boxc/migration/cdm/IndexRedirectCommand.java
src/main/java/edu/unc/lib/boxc/migration/cdm/services/RedirectMappingIndexService.java
src/test/java/edu/unc/lib/boxc/migration/cdm/IndexRedirectCommandIT.java
src/test/java/edu/unc/lib/boxc/migration/cdm/SubmitSipsCommandIT.java
src/test/java/edu/unc/lib/boxc/migration/cdm/services/RedirectMappingIndexServiceTest.java
src/test/java/edu/unc/lib/boxc/migration/cdm/test/RedirectMappingHelper.java
src/test/java/edu/unc/lib/boxc/migration/cdm/test/SipServiceHelper.java
src/test/resources/redirect_db_connection.properties

https://jira.lib.unc.edu/browse/BXC-3372
This PR does a few things:
- builds the command class for indexing the redirect mapping csv to the DB
- code that takes the file path of the properties file which has the DB credentials and uses that to generate a connection string to the DB
- differentiates between using MySQL on the actual servers and sqlite for the tests
- adds IT for command class and one more RedirectMappingService test that builds the connection string
There is a second part TBD which will be on the boxc-ansible repo that takes care of the properties files on each server.

Bxc 3372 connect redirect service to dbs

---

.github/workflows/build.yml
src/test/java/edu/unc/lib/boxc/migration/cdm/DescriptionsCommandIT.java
src/test/java/edu/unc/lib/boxc/migration/cdm/validators/DescriptionsValidatorTest.java

https://jira.lib.unc.edu/browse/BXC-3427

BXC-3427 - Update to use java 11

---

src/main/java/edu/unc/lib/boxc/migration/cdm/InitializeProjectCommand.java
src/main/java/edu/unc/lib/boxc/migration/cdm/services/FindingAidService.java
src/test/java/edu/unc/lib/boxc/migration/cdm/InitializeProjectCommandIT.java
src/test/java/edu/unc/lib/boxc/migration/cdm/services/FindingAidServiceTest.java
src/test/resources/findingaid_fields.csv

[https://jira.lib.unc.edu/browse/BXC-3337](https://jira.lib.unc.edu/browse/BXC-3337)
- `FindingAidService`: service to check for and record hookId and collectionNumber project properties
- `InitializeProjectCommand`: add FindingAidService to command
- Remaining changes include service tests, command tests, and a test resource.

Bxc 3337 record finding aid

---

src/main/java/edu/unc/lib/boxc/migration/cdm/services/RedirectMappingIndexService.java
src/test/java/edu/unc/lib/boxc/migration/cdm/test/RedirectMappingHelper.java

We need to be able to specify the DB name in the connection string now. Here it is!

BXC-3492 add DB name to connection string as a variable

---

pom.xml
src/main/java/edu/unc/lib/boxc/migration/cdm/CdmFieldsCommand.java
src/main/java/edu/unc/lib/boxc/migration/cdm/services/FieldUrlAssessmentService.java
src/test/java/edu/unc/lib/boxc/migration/cdm/CdmFieldsCommandIT.java
src/test/java/edu/unc/lib/boxc/migration/cdm/services/FieldUrlAssessmentServiceTest.java

Waiting on confirmation of logic, but most of the functionality and tests are finalized. 
This code introduces a service that evaluates CDM fields and looks for URLs. Once it generates a list, it tries each URL to see the subsequent response, and then compiles this into an informational CSV.

Bxc 3512 cdm urls report

---

src/main/java/edu/unc/lib/boxc/migration/cdm/services/SipService.java
src/test/java/edu/unc/lib/boxc/migration/cdm/SipsCommandIT.java
src/test/resources/mods_collections/gilmer_mods_children.xml

https://jira.lib.unc.edu/browse/BXC-3737
* Allow descriptions to be added to files in single file works

BXC-3737 - Allow descriptions to be added to files in single file works

---

src/main/java/edu/unc/lib/boxc/migration/cdm/status/AccessFilesStatusService.java
src/main/java/edu/unc/lib/boxc/migration/cdm/status/SourceFilesStatusService.java
src/main/java/edu/unc/lib/boxc/migration/cdm/status/StatusQueryService.java
src/test/java/edu/unc/lib/boxc/migration/cdm/SourceFilesCommandIT.java

[https://jira.lib.unc.edu/browse/BXC-3697](https://jira.lib.unc.edu/browse/BXC-3697)
- modify query and filter for all non-compound objects
- add tests for the unmapped count of group and compound objects

Bxc 3697 sourcefiles status bug

---

src/main/java/edu/unc/lib/boxc/migration/cdm/services/SipService.java
src/main/java/edu/unc/lib/boxc/migration/cdm/services/sips/CdmToDestMapper.java
src/main/java/edu/unc/lib/boxc/migration/cdm/services/sips/MultiFileWorkGenerator.java
src/main/java/edu/unc/lib/boxc/migration/cdm/services/sips/SipPremisLogger.java
src/main/java/edu/unc/lib/boxc/migration/cdm/services/sips/WorkGenerator.java
src/main/java/edu/unc/lib/boxc/migration/cdm/services/sips/WorkGeneratorFactory.java

There are no functional changes in this PR, just splitting up SipService before making additions to it since it is already too long

Pre-BXC-3826 - Split up SipService

---

src/main/java/edu/unc/lib/boxc/migration/cdm/model/DestinationSipEntry.java
src/test/java/edu/unc/lib/boxc/migration/cdm/services/SipServiceTest.java

https://jira.lib.unc.edu/browse/BXC-3876

BXC-3876 - Switch collections created by chompb to being staff only

---

src/main/java/edu/unc/lib/boxc/migration/cdm/services/SipService.java

This PR adds two progress bars to the `generateSips` command to show progress of the two loops.
https://jira.lib.unc.edu/browse/BXC-3897

Bxc 3897 sips progress

---

src/main/java/edu/unc/lib/boxc/migration/cdm/services/CdmIndexService.java
src/main/java/edu/unc/lib/boxc/migration/cdm/services/sips/MultiFileWorkGenerator.java
src/main/java/edu/unc/lib/boxc/migration/cdm/services/sips/OrderedWorkGenerator.java
src/main/java/edu/unc/lib/boxc/migration/cdm/services/sips/WorkGeneratorFactory.java
src/test/java/edu/unc/lib/boxc/migration/cdm/services/CdmIndexServiceTest.java
src/test/java/edu/unc/lib/boxc/migration/cdm/services/SipServiceTest.java
src/test/resources/descriptions/mini_keepsakes/image/620.cpd

https://jira.lib.unc.edu/browse/BXC-3752

BXC-3752 - Compound object children order

---

src/main/java/edu/unc/lib/boxc/migration/cdm/CLIMain.java
src/main/java/edu/unc/lib/boxc/migration/cdm/FilterIndexCommand.java
src/main/java/edu/unc/lib/boxc/migration/cdm/options/IndexFilteringOptions.java
src/main/java/edu/unc/lib/boxc/migration/cdm/services/DescriptionsService.java
src/main/java/edu/unc/lib/boxc/migration/cdm/services/IndexFilteringService.java
src/test/java/edu/unc/lib/boxc/migration/cdm/FilterIndexCommandIT.java
src/test/java/edu/unc/lib/boxc/migration/cdm/services/IndexFilteringServiceTest.java

https://jira.lib.unc.edu/browse/BXC-3230
* Allows for projects to be filtered to a subset of items within the original CDM collection, so that large projects can be processed in smaller parts.

BXC-3230 - Split projects into subsets

---

src/main/java/edu/unc/lib/boxc/migration/cdm/AggregateFilesCommand.java
src/main/java/edu/unc/lib/boxc/migration/cdm/CLIMain.java
src/main/java/edu/unc/lib/boxc/migration/cdm/SipsCommand.java
src/main/java/edu/unc/lib/boxc/migration/cdm/model/MigrationProject.java
src/main/java/edu/unc/lib/boxc/migration/cdm/model/SourceFilesInfo.java
src/main/java/edu/unc/lib/boxc/migration/cdm/options/AggregateFileMappingOptions.java
src/main/java/edu/unc/lib/boxc/migration/cdm/services/AggregateFileMappingService.java
src/main/java/edu/unc/lib/boxc/migration/cdm/services/CdmExportFilesService.java
src/main/java/edu/unc/lib/boxc/migration/cdm/services/SipService.java
src/main/java/edu/unc/lib/boxc/migration/cdm/services/SourceFileService.java
src/main/java/edu/unc/lib/boxc/migration/cdm/services/sips/OrderedWorkGenerator.java
src/main/java/edu/unc/lib/boxc/migration/cdm/services/sips/WorkGenerator.java
src/main/java/edu/unc/lib/boxc/migration/cdm/services/sips/WorkGeneratorFactory.java
src/main/java/edu/unc/lib/boxc/migration/cdm/status/SourceFilesStatusService.java
src/main/java/edu/unc/lib/boxc/migration/cdm/validators/AggregateFilesValidator.java
src/main/java/edu/unc/lib/boxc/migration/cdm/validators/SourceFilesValidator.java
src/test/java/edu/unc/lib/boxc/migration/cdm/AbstractCommandIT.java
src/test/java/edu/unc/lib/boxc/migration/cdm/AggregateFilesCommandIT.java
src/test/java/edu/unc/lib/boxc/migration/cdm/CompleteMigrationIT.java
src/test/java/edu/unc/lib/boxc/migration/cdm/ExportUnmappedSourceFilesIT.java
src/test/java/edu/unc/lib/boxc/migration/cdm/services/AggregateFileMappingServiceTest.java
src/test/java/edu/unc/lib/boxc/migration/cdm/services/SipServiceTest.java
src/test/java/edu/unc/lib/boxc/migration/cdm/services/SourceFileServiceTest.java
src/test/java/edu/unc/lib/boxc/migration/cdm/test/SipServiceHelper.java

https://jira.lib.unc.edu/browse/BXC-4130
* Feature for adding aggregate files to the top and bottom of works
* Integrate with sip generation
* Add tests

BXC-4130 - Add aggregate mappings

---

src/main/java/edu/unc/lib/boxc/migration/cdm/CLIMain.java
src/main/java/edu/unc/lib/boxc/migration/cdm/PermissionsCommand.java
src/test/java/edu/unc/lib/boxc/migration/cdm/PermissionsCommandIT.java
src/test/java/edu/unc/lib/boxc/migration/cdm/services/PermissionsServiceTest.java

[https://unclibrary.atlassian.net/browse/BXC-4378](https://unclibrary.atlassian.net/browse/BXC-4378)
- `PermissionsCommand`: add `PermissionsCommand` class, `generate` subcommand, and tests
- add `PermissionsCommand` to `CLIMain`

BXC-4378 permissions command

---

src/main/java/edu/unc/lib/boxc/migration/cdm/status/SourceFilesSummaryService.java
src/test/java/edu/unc/lib/boxc/migration/cdm/AccessFilesCommandIT.java
src/test/java/edu/unc/lib/boxc/migration/cdm/AggregateFilesCommandIT.java
src/test/java/edu/unc/lib/boxc/migration/cdm/SourceFilesCommandIT.java
src/test/java/edu/unc/lib/boxc/migration/cdm/status/SourceFilesSummaryServiceTest.java

[https://unclibrary.atlassian.net/browse/BXC-4408](https://unclibrary.atlassian.net/browse/BXC-4408)
Display a sample of new files mapped
- `SourceFilesSummaryService`: add `completeListNewFiles`, `sampleListNewFiles`, `listNewFiles` and `showFiles` methods
- modify tests to check for sample of new files mapped

BXC-4408 sample files output

---

src/main/java/edu/unc/lib/boxc/migration/cdm/AccessFilesCommand.java
src/main/java/edu/unc/lib/boxc/migration/cdm/AggregateFilesCommand.java
src/main/java/edu/unc/lib/boxc/migration/cdm/SourceFilesCommand.java
src/main/java/edu/unc/lib/boxc/migration/cdm/options/Verbosity.java
src/main/java/edu/unc/lib/boxc/migration/cdm/status/SourceFilesSummaryService.java
src/test/java/edu/unc/lib/boxc/migration/cdm/SourceFilesCommandIT.java
src/test/java/edu/unc/lib/boxc/migration/cdm/status/SourceFilesSummaryServiceTest.java

[https://unclibrary.atlassian.net/browse/BXC-4409](https://unclibrary.atlassian.net/browse/BXC-4409)
- `SourceFilesSummaryService`: add verbose output to summary method
- add tests

BXC-4409 source_files verbose output

---

src/main/java/edu/unc/lib/boxc/migration/cdm/services/FieldUrlAssessmentService.java
src/test/java/edu/unc/lib/boxc/migration/cdm/services/FieldUrlAssessmentServiceTest.java

https://unclibrary.atlassian.net/browse/BXC-4536
* Don't add empty urls or URLs that are too short to be valid to the list for the report (caused by wonky spacing in urls in the metadata like `http: // auxwe b.du ke.edu/ boxoffice/`)
* Reduce default logging of errors when attempting to access urls. 
* Turn regex into a constant

BXC-4536 - URL report handle empty URLs

---

src/main/java/edu/unc/lib/boxc/migration/cdm/options/IndexFilteringOptions.java
src/main/java/edu/unc/lib/boxc/migration/cdm/options/SipGenerationOptions.java
src/main/java/edu/unc/lib/boxc/migration/cdm/services/RedirectMappingService.java
src/main/java/edu/unc/lib/boxc/migration/cdm/services/SipService.java
src/test/java/edu/unc/lib/boxc/migration/cdm/services/SipServiceTest.java

[https://unclibrary.atlassian.net/browse/BXC-4578](https://unclibrary.atlassian.net/browse/BXC-4578)
- `SipGenerationOptions`: add `-sc`/`--suppress-collection-redirect` flag, getter, and setter
- `RedirectMappingService`: add conditional to suppress collection redirects if `options.isSuppressCollectionRedirect` is true
- add options param to `addCollectionRow` method in `RedirectMappingService` and `SipService`
- add test

BXC-4578 add flag to suppress collection level redirects

---

.github/workflows/build.yml
README.md
pom.xml
src/test/java/edu/unc/lib/boxc/migration/cdm/CompleteMigrationIT.java
src/test/java/edu/unc/lib/boxc/migration/cdm/SubmitSipsCommandIT.java

https://unclibrary.atlassian.net/browse/BXC-4633

BXC-4633 - Use external redis for tests

---

pom.xml
src/main/java/edu/unc/lib/boxc/migration/cdm/CLIMain.java
src/main/java/edu/unc/lib/boxc/migration/cdm/ListProjectsCommand.java
src/main/java/edu/unc/lib/boxc/migration/cdm/services/ListProjectsService.java
src/test/java/edu/unc/lib/boxc/migration/cdm/ListProjectsCommandIT.java
src/test/java/edu/unc/lib/boxc/migration/cdm/services/ListProjectsServiceTest.java

[https://unclibrary.atlassian.net/browse/BXC-4678](https://unclibrary.atlassian.net/browse/BXC-4678)
- add jackson version to `pom.xml`
- `ListProjectsCommand`: output a pretty printed JSON list of all chompb projects in a directory
- `ListProjectsService`: `listProjects` that returns list of projects and info in a JSON node, helper methods `status` and `allowedActions`, `initializeProject`

BXC-4678 chompb command to list projects

---

src/main/java/edu/unc/lib/boxc/migration/cdm/jobs/VelocicroptorRemoteJob.java
src/main/java/edu/unc/lib/boxc/migration/cdm/options/ProcessSourceFilesOptions.java
src/test/java/edu/unc/lib/boxc/migration/cdm/jobs/VelocicroptorRemoteJobTest.java

https://unclibrary.atlassian.net/browse/BXC-4677
* Add job for performing velocicroptor action
* there is not a command for executing it yet, that is BXC-4689, so this is not manually testable yet

BXC-4677 - Add job for performing velocicroptor action

---

src/main/java/edu/unc/lib/boxc/migration/cdm/services/CdmIndexService.java
src/test/java/edu/unc/lib/boxc/migration/cdm/services/CdmIndexServiceTest.java
src/test/resources/descriptions/gilmer_nested_xml/index/description/desc.all

https://unclibrary.atlassian.net/browse/BXC-4809
* Ignore closing html tags to avoid closing a field at the wrong time

BXC-4809 - Html tags in desc.all files

---

src/main/java/edu/unc/lib/boxc/migration/cdm/services/GroupMappingService.java
src/test/java/edu/unc/lib/boxc/migration/cdm/services/GroupMappingServiceTest.java
src/test/java/edu/unc/lib/boxc/migration/cdm/test/SipServiceHelper.java

[https://unclibrary.atlassian.net/browse/BXC-4824](https://unclibrary.atlassian.net/browse/BXC-4824)
- add ' around `firstChild` in `createGroupedWorkEntry` query
- add test

BXC-4824 fix group_mapping sync failing for non-cdm project

---

.github/workflows/build.yml
src/main/java/edu/unc/lib/boxc/migration/cdm/BoxctronFileCommand.java
src/main/java/edu/unc/lib/boxc/migration/cdm/options/BoxctronFileMappingOptions.java
src/main/java/edu/unc/lib/boxc/migration/cdm/services/BoxctronFileService.java
src/test/java/edu/unc/lib/boxc/migration/cdm/BoxctronFileCommandTest.java
src/test/java/edu/unc/lib/boxc/migration/cdm/services/BoxctronFileServiceTest.java
src/test/java/edu/unc/lib/boxc/migration/cdm/test/SipServiceHelper.java

[https://unclibrary.atlassian.net/browse/BXC-4843](https://unclibrary.atlassian.net/browse/BXC-4843)
- add `-e, --exclusion-csv` option
- add `EXCLUSIONS_CSV_HEADERS` and rename `DATA_CSV_HEADERS` to `BOXCTRON_CSV_HEADERS`
- add `gatherExclusionPaths` helper method
- add tests
- update build.yml actions to v3 and v4 (or build fails)

BXC-4843 boxctron command accept exclusions

---

src/main/java/edu/unc/lib/boxc/migration/cdm/services/DescriptionsService.java
src/test/java/edu/unc/lib/boxc/migration/cdm/services/DescriptionsServiceTest.java

https://unclibrary.atlassian.net/browse/BXC-4981
* Close streams during description expand operation to fix issue of running out of handles in a large collection.
* Add a unit test for the generate command

BXC-4981 - Fix too many file handles during description generate command
